### ISSUE TITLE
ros_qtc_plugin cannot be build with Qt Creator 4.6

### ISSUE THREAD

**Issue by vincent-hui** [ros-industrial/ros_qtc_plugin#240]
I tried compiling ros_qtc_plugin with Qt Creator 4.6, but compilation fails.

**Comment by Levi-Armstrong** [comment]
I just merged a PR that got everything working with 4.5 along with fixing several issues. Do you mind trying it again?

**Comment by vincent-hui** [comment]
compilation fails again. Qt Creator Plugin classes changed again.

In file included from ../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.h:25:0,
                 from ../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.cpp:21:
../../../ros_qtc_plugin/src/project_manager/ros_project.h:62:23: error: ‘FilesMode’ has not been declared
     QStringList files(FilesMode fileMode) const;
                       ^
In file included from ../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.cpp:23:0:
../../../ros_qtc_plugin/src/project_manager/ros_catkin_make_step.h:107:1: error: expected class-name before ‘{’ token
 {
 ^
../../../ros_qtc_plugin/src/project_manager/ros_catkin_make_step.h:112:43: error: ‘QList<ProjectExplorer::BuildStepInfo> ROSProjectManager::Internal::ROSCatkinMakeStepFactory::availableSteps(ProjectExplorer::BuildStepList*) const’ marked ‘override’, but does not override
     QList<ProjectExplorer::BuildStepInfo> availableSteps(ProjectExplorer::BuildStepList *parent) const override;
                                           ^
../../../ros_qtc_plugin/src/project_manager/ros_catkin_make_step.h:113:33: error: ‘ProjectExplorer::BuildStep* ROSProjectManager::Internal::ROSCatkinMakeStepFactory::create(ProjectExplorer::BuildStepList*, Core::Id)’ marked ‘override’, but does not override
     ProjectExplorer::BuildStep *create(ProjectExplorer::BuildStepList *parent, Core::Id id) override;
                                 ^
../../../ros_qtc_plugin/src/project_manager/ros_catkin_make_step.h:114:33: error: ‘ProjectExplorer::BuildStep* ROSProjectManager::Internal::ROSCatkinMakeStepFactory::restore(ProjectExplorer::BuildStepList*, const QVariantMap&)’ marked ‘override’, but does not override
     ProjectExplorer::BuildStep *restore(ProjectExplorer::BuildStepList *parent, const QVariantMap &map) override;
                                 ^
../../../ros_qtc_plugin/src/project_manager/ros_catkin_make_step.h:115:33: error: ‘ProjectExplorer::BuildStep* ROSProjectManager::Internal::ROSCatkinMakeStepFactory::clone(ProjectExplorer::BuildStepList*, ProjectExplorer::BuildStep*)’ marked ‘override’, but does not override
     ProjectExplorer::BuildStep *clone(ProjectExplorer::BuildStepList *parent, ProjectExplorer::BuildStep *product) override;
                                 ^
In file included from ../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.cpp:24:0:
../../../ros_qtc_plugin/src/project_manager/ros_catkin_tools_step.h:220:1: error: expected class-name before ‘{’ token
 {
 ^
../../../ros_qtc_plugin/src/project_manager/ros_catkin_tools_step.h:225:43: error: ‘QList<ProjectExplorer::BuildStepInfo> ROSProjectManager::Internal::ROSCatkinToolsStepFactory::availableSteps(ProjectExplorer::BuildStepList*) const’ marked ‘override’, but does not override
     QList<ProjectExplorer::BuildStepInfo> availableSteps(ProjectExplorer::BuildStepList *parent) const override;
                                           ^
../../../ros_qtc_plugin/src/project_manager/ros_catkin_tools_step.h:226:33: error: ‘ProjectExplorer::BuildStep* ROSProjectManager::Internal::ROSCatkinToolsStepFactory::create(ProjectExplorer::BuildStepList*, Core::Id)’ marked ‘override’, but does not override
     ProjectExplorer::BuildStep *create(ProjectExplorer::BuildStepList *parent, Core::Id id) override;
                                 ^
../../../ros_qtc_plugin/src/project_manager/ros_catkin_tools_step.h:227:33: error: ‘ProjectExplorer::BuildStep* ROSProjectManager::Internal::ROSCatkinToolsStepFactory::restore(ProjectExplorer::BuildStepList*, const QVariantMap&)’ marked ‘override’, but does not override
     ProjectExplorer::BuildStep *restore(ProjectExplorer::BuildStepList *parent, const QVariantMap &map) override;
                                 ^
../../../ros_qtc_plugin/src/project_manager/ros_catkin_tools_step.h:228:33: error: ‘ProjectExplorer::BuildStep* ROSProjectManager::Internal::ROSCatkinToolsStepFactory::clone(ProjectExplorer::BuildStepList*, ProjectExplorer::BuildStep*)’ marked ‘override’, but does not override
     ProjectExplorer::BuildStep *clone(ProjectExplorer::BuildStepList *parent, ProjectExplorer::BuildStep *product) override;
                                 ^
../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.cpp: In constructor ‘ROSProjectManager::Internal::ROSBuildConfiguration::ROSBuildConfiguration(ProjectExplorer::Target*, ROSProjectManager::Internal::ROSBuildConfiguration*)’:
../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.cpp:64:46: error: no matching function for call to ‘ProjectExplorer::BuildConfiguration::BuildConfiguration(ProjectExplorer::Target*&, ROSProjectManager::Internal::ROSBuildConfiguration*&)’
     m_cmakeBuildType(source->m_cmakeBuildType)
                                              ^
In file included from ../../../ros_qtc_plugin/src/project_manager/ros_project.h:35:0,
                 from ../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.h:25,
                 from ../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.cpp:21:
../../../qt-creator/src/plugins/projectexplorer/buildconfiguration.h:49:14: note: candidate: ProjectExplorer::BuildConfiguration::BuildConfiguration(ProjectExplorer::Target*, Core::Id)
     explicit BuildConfiguration(Target *target, Core::Id id);
              ^
../../../qt-creator/src/plugins/projectexplorer/buildconfiguration.h:49:14: note:   no known conversion for argument 2 from ‘ROSProjectManager::Internal::ROSBuildConfiguration*’ to ‘Core::Id’
../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.cpp:66:22: error: ‘cloneSteps’ was not declared in this scope
     cloneSteps(source);
                      ^
../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.cpp: In constructor ‘ROSProjectManager::Internal::ROSBuildConfigurationFactory::ROSBuildConfigurationFactory(QObject*)’:
../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.cpp:134:38: error: no matching function for call to ‘ProjectExplorer::IBuildConfigurationFactory::IBuildConfigurationFactory(QObject*&)’
     IBuildConfigurationFactory(parent)
                                      ^
In file included from ../../../ros_qtc_plugin/src/project_manager/ros_project.h:35:0,
                 from ../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.h:25,
                 from ../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.cpp:21:
../../../qt-creator/src/plugins/projectexplorer/buildconfiguration.h:124:5: note: candidate: ProjectExplorer::IBuildConfigurationFactory::IBuildConfigurationFactory()
     IBuildConfigurationFactory();
     ^
../../../qt-creator/src/plugins/projectexplorer/buildconfiguration.h:124:5: note:   candidate expects 0 arguments, 1 provided
At global scope:

**Comment by Levi-Armstrong** [comment]
Thank you. I will do a release of 4.5 then get to work on 4.6.

**Comment by vincent-hui** [comment]
Qt Creator 4.6 Beta released http://blog.qt.io/blog/2018/02/07/qt-creator-4-6-beta-released/

**Comment by vincent-hui** [comment]
Qt Creator 4.6 RC released http://blog.qt.io/blog/2018/03/15/qt-creator-4-6-rc-released/
That means Qt Creator 4.6 will be released soon!!

**Comment by Levi-Armstrong** [comment]
I am currently working out solving the installer issues which I should be finished rebuilding everything today or tomorrow. Once that is finished I can move to testing out building it on 4.6.

**Comment by vincent-hui** [comment]
Hi Levi,

Qt Creator 4.6.0 released!!
http://blog.qt.io/blog/2018/03/28/qt-creator-4-6-0-released/

**Comment by vincent-hui** [comment]
Hi Levi,

Can you build ros_qtc_plugin with Qt Creator 4.6 ?

**Comment by vincent-hui** [comment]
Hi Levi,

Qt Creator 4.7 beta is released!
http://blog.qt.io/blog/2018/06/05/qt-creator-4-7-beta-released/

Do you think it is a good idea to support Qt Creator 4.7 and skip Qt Creator 4.6 ?

Thank a lot

**Comment by AgnosticPope** [comment]
Hi Levi, I'm currently in the middle of trying to refactor the plugin to work with the newest version of creator -- so far it's mostly the plugin project structure that's changed -- when I found this bug. Any luck so far, or should I continue down this path?
The other trick, is that I'm working on Indigo currently -- which means Ubuntu 14.04 -- which won't compile Creator with gcc 4.8.4. I had to upgrade to gcc8 (7 probably works too) in order for the latest Creator to compile without errors as well as a newer version of Qt base-line (I'm using 5.11).

**Comment by vincent-hui** [comment]
Qt Creator 4.7 Beta2 released!

http://blog.qt.io/blog/2018/06/21/qt-creator-4-7-beta2-released/

@AgnosticPope Are you using Qt Creator 4.7 ?

**Comment by vincent-hui** [comment]
Qt Creator 4.7 RC released !!

http://blog.qt.io/blog/2018/07/05/qt-creator-4-7-rc-released

**Comment by Jmeyer1292** [comment]
@Levi-Armstrong Qt Creator 4.7 moving the C++ code model to the Clang Plugin by default seems like a pretty exciting milestone as far as editors go. Allow me to join the din of (unhelpful) voices looking for an upgrade.

**Comment by vincent-hui** [comment]
Hi @AgnosticPope, would you mind telling us the progress of refactoring the plugin?

Thank a lot.

**Comment by vincent-hui** [comment]
Qt Creator 4.8 beta released!! http://blog.qt.io/blog/2018/10/11/qt-creator-4-8-beta-released/

Do you think it is a good idea to support Qt Creator 4.8 and skip Qt Creator 4.7 ?

Thank a lot

**Comment by Levi-Armstrong** [comment]
I have everything building on 4.8. I am currently working on getting a few of the issues addressed and should be able to do a release next week.

**Comment by Levi-Armstrong** [comment]
This is addressed by PR #305. I will close once the installer has been released.

**Comment by vincent-hui** [comment]
Thank @Levi-Armstrong, Qt Creator 4.8 should be released next week.

**Comment by Levi-Armstrong** [comment]
I should have it available to download in the next few hours. I have it released for Xenial and Bionic.

**Comment by Levi-Armstrong** [comment]
It is available for Download! Since the location of the repository has changed. I recommend uninstalling the current version and downloading the new installer so it has the correct repository location to get updates in the future.
