### ISSUE TITLE
It can not compile in qt5.12 with melodic

### ISSUE THREAD

**Issue by loulansuiye** [ros-industrial/ros_qtc_plugin#332]
when I download the source code ,tend to compile it but lots of errors appear as follow:
make[2]: *** [ros_catkin_tools_step.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [ros_catkin_make_step.o] Error 1
In file included from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_project_plugin.cpp:21:0:
../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_project_plugin.h:23:37: fatal error: extensionsystem/iplugin.h: No such file or directory
compilation terminated.
make[2]: *** [remove_directory_dialog.o] Error 1
In file included from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_run_configuration.h:24:0,
                 from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_run_configuration.cpp:21:
../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_run_step.h:24:50: fatal error: projectexplorer/projectconfiguration.h: No such file or directory
compilation terminated.
In file included from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_project_nodes.cpp:21:0:
../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_project_nodes.h:24:42: fatal error: projectexplorer/projectnodes.h: No such file or directory
compilation terminated.
make[2]: *** [ros_project_plugin.o] Error 1
make[2]: *** [ros_project_nodes.o] Error 1
In file included from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_package_wizard.cpp:21:0:
../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_package_wizard.h:24:39: fatal error: coreplugin/basefilewizard.h: No such file or directory
compilation terminated.
make[2]: *** [ros_run_configuration.o] Error 1
Makefile:675: recipe for target 'ros_package_wizard.o' failed
make[2]: *** [ros_package_wizard.o] Error 1
In file included from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_project_manager.h:25:0,
                 from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_project_manager.cpp:21:
../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_terminal_pane.h:24:36: fatal error: coreplugin/ioutputpane.h: No such file or directory
compilation terminated.
Makefile:702: recipe for target 'ros_project_manager.o' failed
make[2]: *** [ros_project_manager.o] Error 1
In file included from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_workspace_watcher.h:24:0,
                 from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_project.h:25,
                 from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_project.cpp:21:
../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_utils.h:27:29: fatal error: utils/fileutils.h: No such file or directory
compilation terminated.
Makefile:692: recipe for target 'ros_project.o' failed
Makefile:736: recipe for target 'ros_project_wizard.o' failed
In file included from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_project_wizard.h:24:0,
                 from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_project_wizard.cpp:21:
../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_utils.h:27:29: fatal error: utils/fileutils.h: No such file or directory
make[2]: *** [ros_project.o] Error 1
compilation terminated.
make[2]: *** [ros_project_wizard.o] Error 1
In file included from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_build_configuration.h:24:0,
                 from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_build_configuration.cpp:21:
../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_utils.h:27:29: fatal error: utils/fileutils.h: No such file or directory
In file included from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_packagexml_parser.h:24:0,
                 from ../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_packagexml_parser.cpp:22:
../../../ros_qtc_plugin-0.1.8/src/project_manager/ros_utils.h:27:29: fatal error: utils/fileutils.h: No such file or directory
compilation terminated.
compilation terminated.
make[2]: *** [ros_build_configuration.o] Error 1
make[2]: *** [ros_packagexml_parser.o] Error 1
Makefile:639: recipe for target 'ros_build_configuration.o' failed
Makefile:680: recipe for target 'ros_packagexml_parser.o' failed
make[2]: Leaving directory '/home/dev/qt/build-ros_qtc_plugin-Qt_5_5_1_qt5-Debug/src/project_manager'
Makefile:42: recipe for target 'sub-project_manager-make_first-ordered' failed
make[1]: Leaving directory '/home/dev/qt/build-ros_qtc_plugin-Qt_5_5_1_qt5-Debug/src'
Makefile:43: recipe for target 'sub-src-make_first-ordered' failed

**Comment by loulansuiye** [comment]
It looks that lots of headers has been removed by the qt or ros supporter

**Comment by oxoocoffee** [comment]
I just build Qt Creator v4.8.2 (ROS melodic, Ubuntu bionic, Qt 5.12.2, RQT master) and did noticed one problem with setup script which I already fixed and will push. Could you attach your setup.log file?
